name: PR Gatekeeper

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Print target branch
        run: 'echo "PR target branch: ${{ github.base_ref }}"'

      - name: Print PR number
        run: 'echo "PR number: #${{ github.event.pull_request.number }}"'

      - name: Complete
        run: echo "Gatekeeper checks complete"